const console = require('console');
const {translate, addPhrase} = require('n-lingual');
console.log(translate(0));
console.log(translate(0));
console.log(translate(1));
console.log(translate());
const foo = addPhrase(0);
console.log(translate(foo));
require('./foo');
require('./bar');
