language: node_js
node_js:
- '9'
- '8'
- '7'
- '6'
install:
- npm install
- npm install -g nyc eslint
script:
- npm run test_coverage
- npm run lint
after_success:
- npm install -g codecov
- codecov
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: Adh54EaKIoIT17kvrTaFZHRRpSKgphlUgYTyw754qxKEteFiaSAtPmTjpVXUtPLkhFCEAvs9Nrkh3G6QThFn+QmEwR4BASW5/Dy1/CwRy6v4TPTcFoblPCruywGxsu077Pa/CEolv/eeZYCiBLZ4UwFnO9owTw+Bx9Cgggn4hPCZZXTzc4KGOXl9fRQ3MMOPktySXQN0L1x0dNZs5+rrxr/v+gtDiwRplDZaxxC4GgRI4UQU8Rp/oVUm6FBIERGahcaaQaAsZKelk2qdmhsN4lTnIs5H5upsVc+mZLhq/3fHRiKZ168L750WFXGsKC2hu/e5e658pQbgy21HvnnjeV6T6Gn+k+faf6xMG2YoWe/XG5U4o86iaRuqF3IHUzQStzVA9+sxLGJC5Ud667BZd5ae626W3O7/A+1e4nvlBQYEMZps6HIk1Pw3fRPBOGT7ClRaBc1W/GBXEZJTi0mSdEYmo0cM+1RxDgXrnMpWZFn84EBssWV4SQkp4w4anXYLXdWf+DRzrZvkGNP34JLnCCr5Tod+anRDjC5yWczB9GqaEw2AHNr1nBpPBZIon3LNFbC26F3tBojdvjUznjLNcSB5dcF/hCqB8fkqwxIc+D0sImtr8vt5Td2saQvLhvWsZx9F+ix4xtKDvN1/g+f8JIJR42MAGUO8GTyCcwez3vI=
  on:
    tags: true
    repo: kei-ito/n-lingual
